
version: '2'
services:
  web:
    image:  node
  rethinkdb:
    image: rethinkdb
    ports:
        - "8080"
        - "28015"
        - "29015"
  redis:
    image: "redis"
  redis5:
    image: "redis"
